server:
  port: 9001

spring:
  application:
    name: api-gateway

  constraints:
    blockedPath:
#      clearTodos: todos/clear
      createToken: api/security
    userMicroserviceIdentifier: secret-key

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            # allowCredentials: true
      routes:
#        - id: todo-service
#          uri: lb://todos
#          predicates:
#            - Path=/api/todos/**

        - id: user-service
          uri: lb://users
          predicates:
            - Path=/api/users/**

        - id: eureka-server
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**


eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/ # for local development

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionRouteLocator: INFO
