server:
  # address: ::1
  port: 9001

spring:
  application:
    name: api-gateway

  constraints:
    blockedPath:
      createToken: api/security
    userMicroserviceIdentifier: secret-key

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:

        - id: user-service
          uri: http://users.railway.internal:9002
          predicates:
            - Path=/api/users/**

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionRouteLocator: INFO
