server:
  address: "::"
  port: 9002

spring:
  application:
    name: users

  datasource:
    # url: jdbc:postgresql://localhost:5432/usersdbfor local development
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  constraints:
    users:
      url: http://users/api/users
      path: /api/users
    security:
      url: http://api-gateway:9001/api/security
      path: /api/security
    userMicroserviceIdentifier: secret-key

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR

