server:
  port: 9002

spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://users-db:5432/usersdb
    # url: jdbc:postgresql://localhost:5432/usersdbfor local development
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  constraints:
    users:
      url: http://users/api/users
      path: /api/users
    security:
      url: http://api-gateway/api/security
      path: /api/security
    userMicroserviceIdentifier: secret-key

eureka:
  client:
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/ # for local development

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR

